# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a83fa9b44f6bf8ebde776936c5a47673b1695ad7574b17f195c68607edf764f9bc558604643df0f3f5e199508398c92e760f7cbdbc6b70e3a1c1e477bfcbf33

test:
  secret_key_base: 962ec9b5186343b620b87e1d7c56c7edf99ef1b2d4145f3674cb96f9a9ac520e834b1c42888dd91f911c2ec7fa64b7a4d4ea44ed0e07e34536d643eae3ee2112

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
